# Generated by Django 4.2.11 on 2024-04-22 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_product_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(0, 'INERT'), (1, 'PENDING'), (2, 'PROCESSING'), (3, 'SHIPPED'), (4, 'COMPLETED')], default=0),
        ),
    ]
