# Generated by Django 4.2.11 on 2024-04-22 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_price',
        ),
    ]
