# Generated by Django 4.2.11 on 2024-04-29 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_remove_review_author_remove_review_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='products',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(0, 'INERT'), (1, 'PENDING'), (2, 'PROCESSING'), (3, 'SHIPPED'), (4, 'COMPLETED'), (5, 'CANCELLED')], default=1),
        ),
    ]
