# Generated by Django 4.2.11 on 2024-04-29 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_address_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='name',
            field=models.CharField(default='Default address', max_length=200),
        ),
    ]
