# Generated by Django 4.2.11 on 2024-05-13 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_address_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='media/profile_pictures/default.jpg', upload_to='profile_pictures'),
        ),
    ]
